# Generated by Django 6.0.2 on 2026-08-13 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_id', models.UUIDField(blank=True, null=True)),
                ('operation', models.CharField(help_text='create|update|delete', max_length=20)),
                ('entity_type', models.CharField(help_text='game_score|quiz_result|lesson_completion|progress', max_length=50)),
                ('local_id', models.CharField(max_length=100)),
                ('server_id', models.CharField(blank=True, max_length=100)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('CONFLICT', 'Conflict')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_log',
                'ordering': ['created_at'],
            },
        ),
    ]
