# Generated by Django 6.0.2 on 2026-08-13 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('game_type', models.CharField(choices=[('alphabet_match', 'Alphabet Matching'), ('number_match', 'Number Matching'), ('memory_cards', 'Memory Cards'), ('shape_sorter', 'Shape Sorter'), ('counting', 'Counting Game'), ('color_match', 'Color Matching'), ('drag_drop', 'Drag and Drop')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('config_json', models.JSONField(default=dict, help_text='Game levels, items, difficulties')),
                ('max_level', models.PositiveIntegerField(default=3)),
                ('icon_emoji', models.CharField(default='🎮', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='learning.learningmodule')),
            ],
            options={
                'db_table': 'games_game',
                'ordering': ['title'],
            },
        ),
    ]
