# Generated by Django 6.0.2 on 2026-08-13 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('alphabet', 'Alphabet'), ('numbers', 'Numbers'), ('colors', 'Colors'), ('shapes', 'Shapes'), ('animals', 'Animals'), ('fruits', 'Fruits & Vegetables'), ('words', 'Basic Words'), ('stories', 'Stories'), ('mathematics', 'Mathematics'), ('english', 'English')], max_length=20)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('icon_emoji', models.CharField(default='📚', max_length=10)),
                ('color_hex', models.CharField(default='#6C63FF', max_length=7)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_module',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_json', models.JSONField(default=dict, help_text='Lesson content: slides, activities, text')),
                ('audio_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=120)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.learningmodule')),
            ],
            options={
                'db_table': 'learning_lesson',
                'ordering': ['order'],
            },
        ),
    ]
