# Generated by Django 6.0.2 on 2026-08-13 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('games', '0001_initial'),
        ('learning', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('local_id', models.CharField(blank=True, help_text='Client-side UUID for sync deduplication', max_length=100)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='children.childprofile')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game')),
            ],
            options={
                'db_table': 'progress_game_score',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('answers_json', models.JSONField(default=list, help_text='List of {question_id, answer_id, is_correct}')),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='children.childprofile')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.quiz')),
            ],
            options={
                'db_table': 'progress_quiz_result',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('first_lesson', 'First Lesson! 🌟'), ('lesson_streak_3', '3-Day Streak! 🔥'), ('lesson_streak_7', 'Week Warrior! 🏆'), ('perfect_quiz', 'Quiz Champion! 🎯'), ('game_master', 'Game Master! 🎮'), ('alphabet_complete', 'ABC Expert! 🔤'), ('numbers_complete', 'Number Ninja! 🔢'), ('colors_complete', 'Color Wizard! 🎨'), ('shapes_complete', 'Shape Star! ⭐'), ('animals_complete', 'Animal Friend! 🐾'), ('all_modules', 'Super Learner! 🚀')], max_length=30)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='children.childprofile')),
            ],
            options={
                'db_table': 'progress_badge',
                'unique_together': {('child', 'badge_type')},
            },
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to='children.childprofile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='learning.lesson')),
            ],
            options={
                'db_table': 'progress_lesson_completion',
                'unique_together': {('child', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent_complete', models.FloatField(default=0.0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='children.childprofile')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.learningmodule')),
            ],
            options={
                'db_table': 'progress_progress',
                'unique_together': {('child', 'module')},
            },
        ),
    ]
