# Generated by Django 6.0.2 on 2026-08-13 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(choices=[('bear', 'Bear'), ('cat', 'Cat'), ('dog', 'Dog'), ('elephant', 'Elephant'), ('fox', 'Fox'), ('lion', 'Lion'), ('owl', 'Owl'), ('penguin', 'Penguin')], default='bear', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pin', models.CharField(blank=True, help_text='4-digit PIN for offline child login', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'children_childprofile',
                'ordering': ['name'],
            },
        ),
    ]
